spring:
  application:
    name: dj-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      stat-view-servlet:
        allow: true
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20

server:
  port: 33001

mybatis:
    type-aliases-package: com.dj.user.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.dj.user.dao.BaseDao
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql